function cross_decoding2(params, response_type, state) 
%% FIRST-LEVEL ANALYSES
% To be ran on server with the outputs from the prepare_data_final_version() function.

% Original script from Johannes Fahrenfort (2018).
% cfg.anti_alias = 'no'; FOR TIMING EFFECTS (see doc)
% cfg.bintrain = to average training events?

%% GENERAL SPECIFICATIONS OF THE EXPERIMENT

% 1) Folders location

server = 1; % 1 = running on server, other = running on laptop

if server == 1
    basefolder = '/home/js2715/';
    datafolder = [basefolder, 'rds/rds-tb419-bekinschtein/Joaquim/DATA (see Yanzhis folder)/READY/PAPER_LAST_VERSION/CF/CD_SHORTEN'];
    scriptfolder = [basefolder, 'metacognition/'];
    resultfolder = [basefolder, 'rds/rds-tb419-bekinschtein/Joaquim/RESULTS/PAPER_LAST_VERSION/CROSSDECODING/CF'];
else
    basefolder = 'C:\Metacognition_Project\';
    datafolder = [basefolder, 'DATA'];
    scriptfolder = [basefolder, 'SCRIPTS'];
    resultfolder = [basefolder, 'RESULTS_LP'];
end

% 2) Find files

cd(datafolder) % go to data folder WITH ALL REQUIRED FILES
% filenames = {dir(sprintf('%s*eventCodes*.set',params{1,1}))};
% filenames = {filenames{1,1}.name};

% if server == 1
%     cd(datafolder) % go to data folder
%     filenames = {dir(sprintf('%s*eventCodes*.set',params{1,1}))};
%     filenames = {filenames{1,1}.name}; 
%     awake_filenames = file_list_restrict(filenames, 'W');     % only awake files 
%     drowsy_filenames = file_list_restrict(filenames, 'S');    % only drowsy files
% else
%     cd(datafolder)
%     filenames = {dir(sprintf('*eventCodes*.set'))};
%     filenames = {filenames{1,1}.name}; 
%     awake_filenames = file_list_restrict(filenames, 'W');     % only awake files 
%     drowsy_filenames = file_list_restrict(filenames, 'S');    % only drowsy files
% end
    
cd(scriptfolder); % go to scripts folder

% 3) EVENT CODES SPECIFICATION (not needed here)

% event code specifications for first-level decisions
tone = 11;
cone = 12; 

% event code specifications for confidence decisions
low_confidence = 13;
high_confidence = 14;

% event codes for motor responses
% up = 15;
% down = 16;

% subjects = {'105','107','108','109','111','112','113','116','119','120','121','123','124','125','128','130','131','132','133','135','137','139','143','145','146'};

% 4) GENERAL ANALYSIS CONFIGURATION SETTINGS
cfg = [];                                          % clear the config variable 
cfg.datadir = datafolder;                          % this is where the data files are
cfg.model = 'BDM';                                 % backward decoding ('BDM') or forward encoding ('FEM')
cfg.raw_or_tfr = 'raw';                            % classify raw or time frequency representations ('tfr')
cfg.nfolds = 1;                                   % the number of folds to use (TO CHANGE TO 1 IF ACROSS SUBJECTS)
cfg.class_method = 'AUC';             	           % the performance measure to use
cfg.crossclass = 'yes';                            % whether to compute temporal generalization
cfg.channelpool = 'ALL_NOSELECTION';               % the channel selection to use 

% we might want to use a larger Hz? Ask Andrés or Johannes!!!
% we try 128Hz instead of 64Hz as that is what Cate did
cfg.resample = 64;                                % downsample (useful for temporal generalization); see if 64Hz or 128Hz
cfg. save_confidence = 'yes';                      % we save confidence scores for post hoc analyses

% the baseline correction was changed from [-.1,0] to [-.25,0]; this might improve the data:
cfg.erp_baseline = [-.2,0];                       % baseline correction in sec. ('no' for no correction) --> do we have pre-trial data for awake session?

%% SPECIFIC SETTINGS FOR EACH OF THE FOUR FIRST LEVEL ANALYSES

if strcmp(response_type, 'CF') && strcmp(state, 'W')
    % AWAKE ACROSS DECISIONS
%     cfg.filenames = awake_filenames;
%     % specifies filenames (awake in this case) 

cfg.filenames = {'102_clean_shorten_eventCodes_W_2;102_clean_shorten_eventCodes_S_2'...
        '105_clean_shorten_eventCodes_W_2;105_clean_shorten_eventCodes_S_2'...
        '106_clean_shorten_eventCodes_W_2;106_clean_shorten_eventCodes_S_2'...
        '107_clean_shorten_eventCodes_W_2;107_clean_shorten_eventCodes_S_2'...
        '111_clean_shorten_eventCodes_W_2;111_clean_shorten_eventCodes_S_2'... 
        '112_clean_shorten_eventCodes_W_2;112_clean_shorten_eventCodes_S_2'...
        '113_clean_shorten_eventCodes_W_2;113_clean_shorten_eventCodes_S_2'...
        '114_clean_shorten_eventCodes_W_2;114_clean_shorten_eventCodes_S_2'...
        '116_clean_shorten_eventCodes_W_2;116_clean_shorten_eventCodes_S_2'...
        '117_clean_shorten_eventCodes_W_2;117_clean_shorten_eventCodes_S_2'...
        '119_clean_shorten_eventCodes_W_2;119_clean_shorten_eventCodes_S_2'...
        '120_clean_shorten_eventCodes_W_2;120_clean_shorten_eventCodes_S_2'...
        '121_clean_shorten_eventCodes_W_2;121_clean_shorten_eventCodes_S_2'...
        '123_clean_shorten_eventCodes_W_2;123_clean_shorten_eventCodes_S_2'... 
        '124_clean_shorten_eventCodes_W_2;124_clean_shorten_eventCodes_S_2'... 
        '125_clean_shorten_eventCodes_W_2;125_clean_shorten_eventCodes_S_2'... 
        '126_clean_shorten_eventCodes_W_2;126_clean_shorten_eventCodes_S_2'...
        '127_clean_shorten_eventCodes_W_2;127_clean_shorten_eventCodes_S_2'...
        '128_clean_shorten_eventCodes_W_2;128_clean_shorten_eventCodes_S_2'... 
        '131_clean_shorten_eventCodes_W_2;131_clean_shorten_eventCodes_S_2'...
        '132_clean_shorten_eventCodes_W_2;132_clean_shorten_eventCodes_S_2'...
        '133_clean_shorten_eventCodes_W_2;133_clean_shorten_eventCodes_S_2'...
        '136_clean_shorten_eventCodes_W_2;136_clean_shorten_eventCodes_S_2'...
        '137_clean_shorten_eventCodes_W_2;137_clean_shorten_eventCodes_S_2'... 
        '139_clean_shorten_eventCodes_W_2;139_clean_shorten_eventCodes_S_2'...
        '140_clean_shorten_eventCodes_W_2;140_clean_shorten_eventCodes_S_2'...
        '141_clean_shorten_eventCodes_W_2;141_clean_shorten_eventCodes_S_2'...
        '143_clean_shorten_eventCodes_W_2;143_clean_shorten_eventCodes_S_2'...
        '144_clean_shorten_eventCodes_W_2;144_clean_shorten_eventCodes_S_2'...
        '146_clean_shorten_eventCodes_W_2;146_clean_shorten_eventCodes_S_2'};


%     cfg.filenames = {'105_clean_shorten_eventCodes_W_2;105_clean_shorten_eventCodes_S_2'...
%         '107_clean_shorten_eventCodes_W_2;107_clean_shorten_eventCodes_S_2'...
%         '108_clean_shorten_eventCodes_W_2;108_clean_shorten_eventCodes_S_2'...
%         '109_clean_shorten_eventCodes_W_2;109_clean_shorten_eventCodes_S_2'...
%         '111_clean_shorten_eventCodes_W_2;111_clean_shorten_eventCodes_S_2'... % Cate's
%         '112_clean_shorten_eventCodes_W_2;112_clean_shorten_eventCodes_S_2'...
%         '113_clean_shorten_eventCodes_W_2;113_clean_shorten_eventCodes_S_2'...
%         '116_clean_shorten_eventCodes_W_2;116_clean_shorten_eventCodes_S_2'...
%         '119_clean_shorten_eventCodes_W_2;119_clean_shorten_eventCodes_S_2'...
%         '120_clean_shorten_eventCodes_W_2;120_clean_shorten_eventCodes_S_2'...
%         '121_clean_shorten_eventCodes_W_2;121_clean_shorten_eventCodes_S_2'...
%         '123_clean_shorten_eventCodes_W_2;123_clean_shorten_eventCodes_S_2'... 
%         '124_clean_shorten_eventCodes_W_2;124_clean_shorten_eventCodes_S_2'... % Cate's
%         '125_clean_shorten_eventCodes_W_2;125_clean_shorten_eventCodes_S_2'... % Cate's
%         '128_clean_shorten_eventCodes_W_2;128_clean_shorten_eventCodes_S_2'... % Cate's
%         '130_clean_shorten_eventCodes_W_2;130_clean_shorten_eventCodes_S_2'... % Cate's
%         '131_clean_shorten_eventCodes_W_2;131_clean_shorten_eventCodes_S_2'...
%         '132_clean_shorten_eventCodes_W_2;132_clean_shorten_eventCodes_S_2'...
%         '133_clean_shorten_eventCodes_W_2;133_clean_shorten_eventCodes_S_2'...
%         '135_clean_shorten_eventCodes_W_2;135_clean_shorten_eventCodes_S_2'...
%         '137_clean_shorten_eventCodes_W_2;137_clean_shorten_eventCodes_S_2'... % Cate's
%         '139_clean_shorten_eventCodes_W_2;139_clean_shorten_eventCodes_S_2'...
%         '143_clean_shorten_eventCodes_W_2;143_clean_shorten_eventCodes_S_2'... % Cate's
%         '145_clean_shorten_eventCodes_W_2;145_clean_shorten_eventCodes_S_2'...
%         '146_clean_shorten_eventCodes_W_2;146_clean_shorten_eventCodes_S_2'};

    % '114_clean_shorten_eventCodes_W_2;114_clean_shorten_eventCodes_S_2'...
    % '129_clean_shorten_eventCodes_W_2;129_clean_shorten_eventCodes_S_2'...
    % '134_clean_shorten_eventCodes_W_2;134_clean_shorten_eventCodes_S_2'...
    % '136_clean_shorten_eventCodes_W_2;136_clean_shorten_eventCodes_S_2'...
    % '140_clean_shorten_eventCodes_W_2;140_clean_shorten_eventCodes_S_2'...

    cfg.class_spec{1} = 13;                      % the first stimulus class
    cfg.class_spec{2} = 14;                      % the second stimulus class
    cfg.outputdir = resultfolder;                 % output location
    cfg.save_confidence = 'yes';
    adam_MVPA_firstlevel(cfg);                                             % run first level analysis
elseif strcmp(response_type, 'CF') && strcmp(state, 'S')
    % DROWSY ACROSS DECISIONS
%     cfg.filenames = drowsy_filenames;                                      % specifies filenames (awake in this case)
    cfg.filenames = {'105_clean_ready_eventCodes_S_1;105_clean_ready_eventCodes_S_2'...
        '107_clean_ready_eventCodes_S_1;107_clean_ready_eventCodes_S_2'...
        '108_clean_ready_eventCodes_S_1;108_clean_ready_eventCodes_S_2'...
        '109_clean_ready_eventCodes_S_1;109_clean_ready_eventCodes_S_2'...
        '112_clean_ready_eventCodes_S_1;112_clean_ready_eventCodes_S_2'...
        '113_clean_ready_eventCodes_S_1;113_clean_ready_eventCodes_S_2'...
        '114_clean_ready_eventCodes_S_1;114_clean_ready_eventCodes_S_2'...
        '116_clean_ready_eventCodes_S_1;116_clean_ready_eventCodes_S_2'...
        '119_clean_ready_eventCodes_S_1;119_clean_ready_eventCodes_S_2'...
        '120_clean_ready_eventCodes_S_1;120_clean_ready_eventCodes_S_2'...
        '121_clean_ready_eventCodes_S_1;121_clean_ready_eventCodes_S_2'...
        '123_clean_ready_eventCodes_S_1;123_clean_ready_eventCodes_S_2'...
        '129_clean_ready_eventCodes_S_1;129_clean_ready_eventCodes_S_2'...
        '131_clean_ready_eventCodes_S_1;131_clean_ready_eventCodes_S_2'...
        '132_clean_ready_eventCodes_S_1;132_clean_ready_eventCodes_S_2'...
        '133_clean_ready_eventCodes_S_1;133_clean_ready_eventCodes_S_2'...
        '134_clean_ready_eventCodes_S_1;134_clean_ready_eventCodes_S_2'...
        '135_clean_ready_eventCodes_S_1;135_clean_ready_eventCodes_S_2'...
        '136_clean_ready_eventCodes_S_1;136_clean_ready_eventCodes_S_2'...
        '139_clean_ready_eventCodes_S_1;139_clean_ready_eventCodes_S_2'...
        '140_clean_ready_eventCodes_S_1;140_clean_ready_eventCodes_S_2'...
        '145_clean_ready_eventCodes_S_1;145_clean_ready_eventCodes_S_2'...
        '146_clean_ready_eventCodes_S_1;146_clean_ready_eventCodes_S_2'};
    cfg.class_spec{1} = 11;                       % the first stimulus class
    cfg.class_spec{2} = 12;                      % the second stimulus class
    cfg.outputdir = resultfolder;                % output location
    cfg.save_confidence = 'yes';
    adam_MVPA_firstlevel(cfg);                                             % run first level analysis
elseif strcmp(response_type, 'PD') && strcmp(state, 'W')

% PERCEPTUAL DECISION ACROSS STATES

cfg.filenames = {'102_clean_shorten_eventCodes_W_1;102_clean_shorten_eventCodes_S_1'...
        '105_clean_shorten_eventCodes_W_1;105_clean_shorten_eventCodes_S_1'...
        '106_clean_shorten_eventCodes_W_1;106_clean_shorten_eventCodes_S_1'...
        '107_clean_shorten_eventCodes_W_1;107_clean_shorten_eventCodes_S_1'...
        '111_clean_shorten_eventCodes_W_1;111_clean_shorten_eventCodes_S_1'... 
        '112_clean_shorten_eventCodes_W_1;112_clean_shorten_eventCodes_S_1'...
        '113_clean_shorten_eventCodes_W_1;113_clean_shorten_eventCodes_S_1'...
        '114_clean_shorten_eventCodes_W_1;114_clean_shorten_eventCodes_S_1'...
        '116_clean_shorten_eventCodes_W_1;116_clean_shorten_eventCodes_S_1'...
        '117_clean_shorten_eventCodes_W_1;117_clean_shorten_eventCodes_S_1'...
        '119_clean_shorten_eventCodes_W_1;119_clean_shorten_eventCodes_S_1'...
        '120_clean_shorten_eventCodes_W_1;120_clean_shorten_eventCodes_S_1'...
        '121_clean_shorten_eventCodes_W_1;121_clean_shorten_eventCodes_S_1'...
        '123_clean_shorten_eventCodes_W_1;123_clean_shorten_eventCodes_S_1'... 
        '124_clean_shorten_eventCodes_W_1;124_clean_shorten_eventCodes_S_1'... 
        '125_clean_shorten_eventCodes_W_1;125_clean_shorten_eventCodes_S_1'... 
        '126_clean_shorten_eventCodes_W_1;126_clean_shorten_eventCodes_S_1'...
        '127_clean_shorten_eventCodes_W_1;127_clean_shorten_eventCodes_S_1'...
        '128_clean_shorten_eventCodes_W_1;128_clean_shorten_eventCodes_S_1'... 
        '131_clean_shorten_eventCodes_W_1;131_clean_shorten_eventCodes_S_1'...
        '132_clean_shorten_eventCodes_W_1;132_clean_shorten_eventCodes_S_1'...
        '133_clean_shorten_eventCodes_W_1;133_clean_shorten_eventCodes_S_1'...
        '136_clean_shorten_eventCodes_W_1;136_clean_shorten_eventCodes_S_1'...
        '137_clean_shorten_eventCodes_W_1;137_clean_shorten_eventCodes_S_1'... 
        '139_clean_shorten_eventCodes_W_1;139_clean_shorten_eventCodes_S_1'...
        '140_clean_shorten_eventCodes_W_1;140_clean_shorten_eventCodes_S_1'...
        '141_clean_shorten_eventCodes_W_1;141_clean_shorten_eventCodes_S_1'...
        '143_clean_shorten_eventCodes_W_1;143_clean_shorten_eventCodes_S_1'...
        '144_clean_shorten_eventCodes_W_1;144_clean_shorten_eventCodes_S_1'...
        '146_clean_shorten_eventCodes_W_1;146_clean_shorten_eventCodes_S_1'};

%     cfg.filenames = {'105_clean_ready_eventCodes_W_1;105_clean_ready_eventCodes_S_1'...
%         '107_clean_ready_eventCodes_W_1;107_clean_ready_eventCodes_S_1'...
%         '108_clean_ready_eventCodes_W_1;108_clean_ready_eventCodes_S_1'...
%         '109_clean_ready_eventCodes_W_1;109_clean_ready_eventCodes_S_1'...
%         '112_clean_ready_eventCodes_W_1;112_clean_ready_eventCodes_S_1'...
%         '113_clean_ready_eventCodes_W_1;113_clean_ready_eventCodes_S_1'...
%         '114_clean_ready_eventCodes_W_1;114_clean_ready_eventCodes_S_1'...
%         '116_clean_ready_eventCodes_W_1;116_clean_ready_eventCodes_S_1'...
%         '119_clean_ready_eventCodes_W_1;119_clean_ready_eventCodes_S_1'...
%         '120_clean_ready_eventCodes_W_1;120_clean_ready_eventCodes_S_1'...
%         '121_clean_ready_eventCodes_W_1;121_clean_ready_eventCodes_S_1'...
%         '123_clean_ready_eventCodes_W_1;123_clean_ready_eventCodes_S_1'...
%         '129_clean_ready_eventCodes_W_1;129_clean_ready_eventCodes_S_1'...
%         '131_clean_ready_eventCodes_W_1;131_clean_ready_eventCodes_S_1'...
%         '132_clean_ready_eventCodes_W_1;132_clean_ready_eventCodes_S_1'...
%         '133_clean_ready_eventCodes_W_1;133_clean_ready_eventCodes_S_1'...
%         '134_clean_ready_eventCodes_W_1;134_clean_ready_eventCodes_S_1'...
%         '135_clean_ready_eventCodes_W_1;135_clean_ready_eventCodes_S_1'...
%         '136_clean_ready_eventCodes_W_1;136_clean_ready_eventCodes_S_1'...
%         '139_clean_ready_eventCodes_W_1;139_clean_ready_eventCodes_S_1'...
%         '140_clean_ready_eventCodes_W_1;140_clean_ready_eventCodes_S_1'...
%         '145_clean_ready_eventCodes_W_1;145_clean_ready_eventCodes_S_1'...
%         '146_clean_ready_eventCodes_W_1;146_clean_ready_eventCodes_S_1'};
    cfg.class_spec{1} = 11;                                 % the first stimulus class
    cfg.class_spec{2} = 12;                                 % the second stimulus class
    cfg.outputdir = resultfolder;
    cfg.save_confidence = 'yes';
    adam_MVPA_firstlevel(cfg);                                             % run first level analysis
elseif strcmp(response_type, 'PD') && strcmp(state, 'S')

   % CONFIDENCE ACROSS STATES
    cfg.filenames = {'105_clean_shorten_eventCodes_W_2;105_clean_shorten_eventCodes_S_2'...
        '107_clean_shorten_eventCodes_W_2;107_clean_shorten_eventCodes_S_2'...
        '108_clean_shorten_eventCodes_W_2;108_clean_shorten_eventCodes_S_2'...
        '109_clean_shorten_eventCodes_W_2;109_clean_shorten_eventCodes_S_2'...
        '112_clean_shorten_eventCodes_W_2;112_clean_shorten_eventCodes_S_2'...
        '113_clean_shorten_eventCodes_W_2;113_clean_shorten_eventCodes_S_2'...
        '114_clean_shorten_eventCodes_W_2;114_clean_shorten_eventCodes_S_2'...
        '116_clean_shorten_eventCodes_W_2;116_clean_shorten_eventCodes_S_2'...
        '119_clean_shorten_eventCodes_W_2;119_clean_shorten_eventCodes_S_2'...
        '120_clean_shorten_eventCodes_W_2;120_clean_shorten_eventCodes_S_2'...
        '121_clean_shorten_eventCodes_W_2;121_clean_shorten_eventCodes_S_2'...
        '123_clean_shorten_eventCodes_W_2;123_clean_shorten_eventCodes_S_2'...
        '129_clean_shorten_eventCodes_W_2;129_clean_shorten_eventCodes_S_2'...
        '131_clean_shorten_eventCodes_W_2;131_clean_shorten_eventCodes_S_2'...
        '132_clean_shorten_eventCodes_W_2;132_clean_shorten_eventCodes_S_2'...
        '133_clean_shorten_eventCodes_W_2;133_clean_shorten_eventCodes_S_2'...
        '134_clean_shorten_eventCodes_W_2;134_clean_shorten_eventCodes_S_2'...
        '135_clean_shorten_eventCodes_W_2;135_clean_shorten_eventCodes_S_2'...
        '136_clean_shorten_eventCodes_W_2;136_clean_shorten_eventCodes_S_2'...
        '139_clean_shorten_eventCodes_W_2;139_clean_shorten_eventCodes_S_2'...
        '140_clean_shorten_eventCodes_W_2;140_clean_shorten_eventCodes_S_2'...
        '145_clean_shorten_eventCodes_W_2;145_clean_shorten_eventCodes_S_2'...
        '146_clean_shorten_eventCodes_W_2;146_clean_shorten_eventCodes_S_2'};
    cfg.class_spec{1} = low_confidence;                                 % the first stimulus class
    cfg.class_spec{2} = high_confidence;                                 % the second stimulus class
    cfg.outputdir = [resultfolder, 'CD'];
    cfg.save_confidence = 'yes';
    adam_MVPA_firstlevel(cfg);    
end

%% The output can now be entered in the second_level script for final decoding analyses.


% SANITY CHECK 1:
%     cfg.filenames = awake_filenames;                                       % specifies filenames (awake in this case)
% cfg.filenames = {'105_clean_ready_eventCodes_W_1;107_clean_ready_eventCodes_W_1'...
%         '107_clean_ready_eventCodes_W_1;108_clean_ready_eventCodes_W_1'...
%         '108_clean_ready_eventCodes_W_1;109_clean_ready_eventCodes_W_1'...
%         '109_clean_ready_eventCodes_W_1;112_clean_ready_eventCodes_W_1'...
%         '112_clean_ready_eventCodes_W_1;113_clean_ready_eventCodes_W_1'...
%         '113_clean_ready_eventCodes_W_1;114_clean_ready_eventCodes_W_1'...
%         '114_clean_ready_eventCodes_W_1;116_clean_ready_eventCodes_W_1'...
%         '116_clean_ready_eventCodes_W_1;119_clean_ready_eventCodes_W_1'...
%         '119_clean_ready_eventCodes_W_1;120_clean_ready_eventCodes_W_1'...
%         '120_clean_ready_eventCodes_W_1;121_clean_ready_eventCodes_W_1'...
%         '121_clean_ready_eventCodes_W_1;123_clean_ready_eventCodes_W_1'...
%         '123_clean_ready_eventCodes_W_1;129_clean_ready_eventCodes_W_1'...
%         '129_clean_ready_eventCodes_W_1;131_clean_ready_eventCodes_W_1'...
%         '131_clean_ready_eventCodes_W_1;132_clean_ready_eventCodes_W_1'...
%         '132_clean_ready_eventCodes_W_1;133_clean_ready_eventCodes_W_1'...
%         '133_clean_ready_eventCodes_W_1;134_clean_ready_eventCodes_W_1'...
%         '134_clean_ready_eventCodes_W_1;135_clean_ready_eventCodes_W_1'...
%         '135_clean_ready_eventCodes_W_1;136_clean_ready_eventCodes_W_1'...
%         '136_clean_ready_eventCodes_W_1;139_clean_ready_eventCodes_W_1'...
%         '139_clean_ready_eventCodes_W_1;140_clean_ready_eventCodes_W_1'...
%         '140_clean_ready_eventCodes_W_1;145_clean_ready_eventCodes_W_1'...
%         '145_clean_ready_eventCodes_W_1;146_clean_ready_eventCodes_W_1'...
%         '146_clean_ready_eventCodes_W_1;105_clean_ready_eventCodes_W_1'};
%     cfg.class_spec{1} = 11;                                 % the first stimulus class
%     cfg.class_spec{2} = 12;                                 % the second stimulus class
%     cfg.outputdir = resultfolder;                    % output location
%     cfg.save_confidence = 'yes';
%     adam_MVPA_firstlevel(cfg);                                             % run first level analysis

%     % SANITY CHECK 2:
% %     cfg.filenames = drowsy_filenames;                                      % specifies filenames (drowsy in this case)
%     cfg.filenames = {'105_clean_ready_eventCodes_S_1;105_clean_ready_eventCodes_S_1'...
%         '107_clean_ready_eventCodes_S_1;107_clean_ready_eventCodes_S_1'...
%         '108_clean_ready_eventCodes_S_1;108_clean_ready_eventCodes_S_1'...
%         '109_clean_ready_eventCodes_S_1;109_clean_ready_eventCodes_S_1'...
%         '112_clean_ready_eventCodes_S_1;112_clean_ready_eventCodes_S_1'...
%         '113_clean_ready_eventCodes_S_1;113_clean_ready_eventCodes_S_1'...
%         '114_clean_ready_eventCodes_S_1;114_clean_ready_eventCodes_S_1'...
%         '116_clean_ready_eventCodes_S_1;116_clean_ready_eventCodes_S_1'...
%         '119_clean_ready_eventCodes_S_1;119_clean_ready_eventCodes_S_1'...
%         '120_clean_ready_eventCodes_S_1;120_clean_ready_eventCodes_S_1'...
%         '121_clean_ready_eventCodes_S_1;121_clean_ready_eventCodes_S_1'...
%         '123_clean_ready_eventCodes_S_1;123_clean_ready_eventCodes_S_1'...
%         '129_clean_ready_eventCodes_S_1;129_clean_ready_eventCodes_S_1'...
%         '131_clean_ready_eventCodes_S_1;131_clean_ready_eventCodes_S_1'...
%         '132_clean_ready_eventCodes_S_1;132_clean_ready_eventCodes_S_1'...
%         '133_clean_ready_eventCodes_S_1;133_clean_ready_eventCodes_S_1'...
%         '134_clean_ready_eventCodes_S_1;134_clean_ready_eventCodes_S_1'...
%         '135_clean_ready_eventCodes_S_1;135_clean_ready_eventCodes_S_1'...
%         '136_clean_ready_eventCodes_S_1;136_clean_ready_eventCodes_S_1'...
%         '139_clean_ready_eventCodes_S_1;139_clean_ready_eventCodes_S_1'...
%         '140_clean_ready_eventCodes_S_1;140_clean_ready_eventCodes_S_1'...
%         '145_clean_ready_eventCodes_S_1;145_clean_ready_eventCodes_S_1'...
%         '146_clean_ready_eventCodes_S_1;146_clean_ready_eventCodes_S_1'};
%     cfg.class_spec{1} = 11;                                 % the first stimulus class
%     cfg.class_spec{2} = 12;                                 % the second stimulus class
%     cfg.outputdir = [resultfolder, 'PD_TEST_DROWSY'];                   % output location
%     cfg.save_confidence = 'yes';
%     adam_MVPA_firstlevel(cfg);                                             % run first level analysis